return {
    addon_name = 'n1k',
    addon_type = 'REST',
    version = 1.0,
    revision = 0,
    classes = {
        n1k = {},
        summary = {
            properties = {
                ip = {type = 'string'},
                name = {type = 'string'},
                version = {type = 'string'},
                -- connectionName = {type = 'string'},
                -- datacenterName = {type = 'string'},
                -- vcIpaddress = {type = 'string'},
                -- vcStatus = {type = 'string'},
                -- vcUuid = {type = 'string'},
                haStatus = {type = 'boolean'},
                mode = {type = 'string'},
                switchMode = {type = 'string'},
            }
        },
        limits = {
            properties = {
                vethUsed = {type = 'number'},
                vethMax = {type = 'number'},
                vemUsed = {type = 'number'},
                vemMax = {type = 'number'},
                portprofilesUsed = {type = 'number'},
                portprofilesMax = {type = 'number'},
                vlansUsed = {type = 'number'},
                vlansMax = {type = 'number'},
                vethPerHostUsed = {type = 'number'},
                vethPerHostMax = {type = 'number'},
                vxlansUsed = {type = 'number'},
                vxlansMax = {type = 'number'},
            }
        },
        license = { 
            key = 'type', 
            properties = {
                available = {type = 'number'},
                expires = {type = 'string'},
                used = {type = 'number'},
                type = {type = 'string'},
                status = {type = 'string'},
            }
        },
        uplink = { 
            key = 'port',
            properties = {
                name = {type = 'string'},
                module = {type = 'number'},
                portChannelType = {type = 'string'},
                packetsTx = {type = 'number'},
                mtu = {type = 'number'},
                cdpPort = {type = 'string'},
                port = {type = 'string'},
                status = {type = 'string'},
                mode = {type = 'string'},
                vlans = {type = 'string'},
                portChannel = {type = 'number'},
                cdpNativeVlan = {type = 'number'},
                portChannelMembers = {type = 'string'},
                ethernet = {type = 'string'},
                packetsRx = {type = 'number'},
                cdpSwitch = {type = 'string'},
                portProfile = {type = 'string'},
                speed = {type = 'string'},
            },
         },
        vnic = { 
            key = 'vnic',
            properties = {
                vnic = {type = 'string'},
                mac = {type = 'string'},
                dvport = {type = 'string'},
                adapter = {type = 'string'},
                hostIP = {type = 'string'},
                vlans = {type = 'string'},
                portGroup = {type = 'string'},
                status = {type = 'string'},
                module = {type = 'number'},
                vm = {type = 'string'},
                vnic = {type = 'string'},
            },

        },
        portProfile = { 
            key = 'name', 
            properties = {
                name = {type = 'string'},
                minPorts = {type = 'number'},
                systemVlans = {type = 'string'},
                nativeVlan = {type = 'number'},
                usedPorts = {type = 'number'},
                vlans = {type = 'string'},
                status = {type = 'string'},
                mode = {type = 'string'},
                maxPorts = {type = 'number'},
                type = {type = 'string'},
            },
        },
        vem = { 
            key = 'module',
            properties = {
                module = {type = 'number'},
                licenseUsage = {type = 'number'},
                esxVersion = {type = 'string'},
                serialnum = {type = 'string'},
                status = {type = 'string'},
                license = {type = 'string'},
                mac = {type = 'string'},
                type = {type = 'string'},
                maxNumVnic = {type = 'number'},
                nSockets = {type = 'number'},
                ports = {type = 'number'},
                -- datacenterName = {type = 'string'},
                numVM = {type = 'number'},
                modmac = {type = 'number'},
                numVnic = {type = 'number'},
                version = {type = 'string'},
                model = {type = 'string'},
                lic_version = {type = 'string'},
                ip = {type = 'string'},
                name = {type = 'string'},
                srvuuid = {type = 'string'},
                -- macUsed = {type = 'number'},
                vethUsed = {type = 'number'},
            },
        },
        vemVnic = { key = 'vnic', 
            properties = {
                mac = {type = 'string'},
                dvport = {type = 'string'},
                adapter = {type = 'string'},
                hostIP = {type = 'string'},
                vlans = {type = 'string'},
                portGroup = {type = 'string'},
                status = {type = 'string'},
                module = {type = 'number'},
                vm = {type = 'string'},
                vnic = {type = 'string'},
            },
        },
        vemPortProfile = { 
            key = 'name', 
            properties = {
                name = {type = 'string'},
                minPorts = {type = 'number'},
                systemVlans = {type = 'string'},
                usedPorts = {type = 'number'},
                vlans = {type = 'string'},
                status = {type = 'string'},
                mode = {type = 'string'},
                maxPorts = {type = 'number'},
                type = {type = 'string'},
            },
        },
        vemUplink = { key = 'port', 
            properties = {
                name = {type = 'string'},
                module = {type = 'number'},
                portChannelType = {type = 'string'},
                packetsTx = {type = 'number'},
                mtu = {type = 'number'},
                cdpPort = {type = 'string'},
                port = {type = 'string'},
                status = {type = 'string'},
                mode = {type = 'string'},
                vlans = {type = 'number'},
                portChannel = {type = 'number'},
                cdpNativeVlan = {type = 'number'},
                portChannelMembers = {type = 'string'},
                ethernet = {type = 'string'},
                packetsRx = {type = 'number'},
                cdpSwitch = {type = 'string'},
                portProfile = {type = 'string'},
                speed = {type = 'string'},
            },
        },
    }
}
